export  const RATING_LOADING= 'RATING_LOADING';
export  const RATING_SUCCESS= 'RATING_SUCCESS';
export  const RATING_ERROR= 'RATING_ERROR';

export  const REVIEW_FOR_PROFILE_LOADING= 'REVIEW_FOR_PROFILE_LOADING';
export  const REVIEW_FOR_PROFILE_SUCCESS= 'REVIEW_FOR_PROFILE_SUCCESS';
export  const REVIEW_FOR_PROFILE_ERROR= 'REVIEW_FOR_PROFILE_ERROR';