export  const PRODUCT_LOADING= 'PRODUCT_LOADING';
export  const PRODUCT_SUCCESS= 'PRODUCT_SUCCESS';
export  const PRODUCT_ERROR= 'PRODUCT_ERROR';

export  const PRODUCTS_LOADING= 'PRODUCTS_LOADING';
export  const PRODUCTS_SUCCESS= 'PRODUCTS_SUCCESS';
export  const PRODUCTS_ERROR= 'PRODUCTS_ERROR';

export  const PAGINATED_PRODUCTS_LOADING= 'PAGINATED_PRODUCTS_LOADING';
export  const PAGINATED_PRODUCTS_SUCCESS= 'PAGINATED_PRODUCTS_SUCCESS';
export  const PAGINATED_PRODUCTS_ERROR= 'PAGINATED_PRODUCTS_ERROR';

export  const SIMILAR_PRODUCTS_LOADING= 'SIMILAR_PRODUCTS_LOADING';
export  const SIMILAR_PRODUCTS_SUCCESS= 'SIMILAR_PRODUCTS_SUCCESS';
export  const SIMILAR_PRODUCTS_ERROR= 'SIMILAR_PRODUCTS_ERROR';