export  const CART_LIST_LOADING= 'CART_LIST_LOADING';
export  const CART_LIST_SUCCESS= 'CART_LIST_SUCCESS';
export  const CART_LIST_ERROR= 'CART_LIST_ERROR';

export  const TOTAL_CART_LOADING= 'TOTAL_CART_LOADING';
export  const TOTAL_CART_SUCCESS= 'TOTAL_CART_SUCCESS';
export  const TOTAL_CART_ERROR= 'TOTAL_CART_ERROR';